---

- name: Install redis packages
  apt:
    pkg:
      - redis-server
      - redis-tools
    state: present

- name: Install the the systemd config
  template:
    src: redis-server.service.j2
    dest: /lib/systemd/system/{{ redis_instance_fullname }}.service

- name: Symlink systemd config into /etc/systemd/system
  file:
    path: /etc/systemd/system/{{ redis_instance_name }}.service
    src: /lib/systemd/system/{{ redis_instance_fullname }}.service
    state: link

- name: Ensure redis data directory exists
  file:
    path: "{{ redis_dir }}"
    state: directory
    owner: redis
    group: redis
    mode: 0750

- name: Install the redis config
  template:
    src: "redis.conf.j2"
    dest: /etc/redis/{{ redis_instance_name }}.conf
  notify: restart redis {{ redis_instance_name }}

- name: Force systemd to reread configs (2.4 and above)
  systemd:
    daemon_reload: yes

- name: Ensure service is enabled
  systemd:
    name: "{{ redis_instance_name }}"
    enabled: yes
