---

- name: Install redis packages
  apt:
    pkg:
      - redis-server
      - redis-tools
    state: present

- name: Install the redis config
  template:
    src: "{{ redis_instance_name }}.conf.j2"
    dest: /etc/redis/{{ redis_instance_name }}.conf
  notify: restart redis

- name: Install the the systemd config
  template:
    src: redis-server.service.j2
    dest: /lib/systemd/system/{{ redis_instance_name }}-server.service

- name: Symlink systemd config into /etc/systemd/system
  file:
    path: /etc/systemd/system/{{ redis_instance_name }}-server.service
    src: /lib/systemd/system/{{ redis_instance_name }}-server.service
    state: link
